### ISSUE TITLE
how to change the default port

### ISSUE THREAD

**Issue by bitcodernull** [tronprotocol/tron-eventquery#12]
the query service default port is 8080
how to change it

**Comment by bitcodernull** [comment]
please add the configuration to config.conf

**Comment by BisonAl** [comment]
Bump on this, am also wondering how to change the default port from 8080.

**Comment by BisonAl** [comment]
Aha found this out!

You can modify https://github.com/tronprotocol/tron-eventquery/blob/master/config.conf with the additional line:
```
server.port=$whateverPort
```

this seems to be Spring framework thing, looking at https://stackoverflow.com/questions/21083170/how-to-configure-port-for-a-spring-boot-application

**Comment by jiangyy0824** [comment]
Close the issue as the problem is solved
