### ISSUE TITLE
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

### ISSUE THREAD

**Issue by davidbongcc** [tronprotocol/tron-eventquery#13]
I have encountered this issue when I try to sync and build.
`Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain`

I reckon that the .mvn folder is missing in this case.
Please advise.

**Comment by jiangyy0824** [comment]
Seems that you run the command with an incorrect folder or maven configuration. Please refer to https://stackoverflow.com/questions/50104172/could-not-find-or-load-main-class-org-apache-maven-wrapper-mavenwrappermain
