### ISSUE TITLE
the  data structure is not the same as https://api.trongrid.io/events/transaction/2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8

### ISSUE THREAD

**Issue by bitcodernull** [tronprotocol/tron-eventquery#20]
on my node , when  i run  
"curl http://127.0.0.1:32222/events/transaction/2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8 ", i got the following data:

`[{"eventSignature":"Transfer(address,address,uint256)","topicMap":{"0":"THqZnzzWcWEtBFwgdFJ5eoreFLbLRoQZkz","1":"TX1J5rycWMCnvBEZM7u5uyTyrJkvkTDawL","from":"THqZnzzWcWEtBFwgdFJ5eoreFLbLRoQZkz","to":"TX1J5rycWMCnvBEZM7u5uyTyrJkvkTDawL"},"dataMap":{"2":"100000000000000000","tokens":"100000000000000000"},"transactionId":"2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8","contractAddress":"TYPHiHUiPBPCNvqBpzy1f7bdqrZ5r8e1K7","callerAddress":"","originAddress":"THqZnzzWcWEtBFwgdFJ5eoreFLbLRoQZkz","creatorAddress":"TT8VsHEmEXHNzyGdogMWz2Vqixn2KLncDi","blockNumber":13541654,"removed":"false","latestSolidifiedBlockNumber":13541635,"timeStamp":1570870884000,"triggerName":"contractEventTrigger","eventSignatureFull":"Transfer(address from,address to,uint256 tokens)","eventName":"Transfer","uniqueId":"2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8_1","abiString":null,"rawData":{"address":"f5e0aec53995fb93588ca656a959ac467523db83","topics":[{"data":"ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"},{"data":"000000000000000000000000564f08f22929e54e9780f0f08464c8a04ea93391"},{"data":"000000000000000000000000e6bfb75fd6a9f73926ef9a580fd2107762497f8e"}],"data":"000000000000000000000000000000000000000000000000016345785d8a0000"}}]`

on the "https://api.trongrid.io/events/transaction/2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8",  the data is :
`[{"caller_contract_address":"TYPHiHUiPBPCNvqBpzy1f7bdqrZ5r8e1K7","transaction_id":"2dc6eed230dac6676389bad13af63ac78d2cab4bf082fa10d8f031ef0eaf6ac8","result":{"from":"0x564f08f22929e54e9780f0f08464c8a04ea93391","tokens":"100000000000000000","to":"0xe6bfb75fd6a9f73926ef9a580fd2107762497f8e"},"result_type":{"from":"address","tokens":"uint256","to":"address"},"block_timestamp":1570870884000,"block_number":13541654,"event_name":"Transfer","contract_address":"TYPHiHUiPBPCNvqBpzy1f7bdqrZ5r8e1K7","event_index":0}]`

it is not the same

**Comment by wubinTron** [comment]
event query and tronogrid are different systems, the most of data is the same. The difference may come from the encoding method and the point of their attention. So you can use which system you based on the requirement.

**Comment by jiangyy0824** [comment]
Close the problem, because it is not a product bug
